services:
  tts:
    build:
      context: ./piper-tts
    user: "10001:10001"
    volumes:
      - ./run:/app/run
      - ./voices_import:/app/voices
      - ./out:/app/out
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    user: "10001:10001"
    ports:
      - "3000:3000"
    volumes:
      - ./api/src:/app/src
      - ./api/node_modules:/app/node_modules
      - ./run:/app/run
      - ./out:/app/out
      - ./voices_import:/app/voices
      - ./voices_import:/app/voices_import
    environment:
      - NODE_ENV=development
      - DELETE_SECONDS=10
